### ISSUE TITLE
Will it work with mongoDB?

### ISSUE THREAD

**Issue by VibhavChaddha** [42BV/jarb#40]
I want to know if it is compatible with MongoDB. If not, then can anyone suggest me one?

**Comment by jeroenvs** [comment]
Jarb's main focus is handling database constraints, column metadata such as types, not null and lengths. Also providing handlers when constraints are violated, e.g. foreign keys and unique keys.

In MongoDB these constraints are not relevant, due to the database being scheme free. When using MongoDB I would suggest implementing these validity checks in your code.
